project:
  type: website
  output-dir: docs

website:
  title: "thinhong"
  google-analytics: "G-RVRBE7Y1R2"
  back-to-top-navigation: true
  navbar:
    left:
      - text: About
        href: about/index.qmd
      - text: Research
        href: https://scholar.google.com/citations?user=PkfvVs0AAAAJ
      - text: Talks
        href: talks.qmd
      - text: Teaching
        href: teaching.qmd
      - text: Software
        href: https://github.com/thinhong
      - text: Blog
        href: blog.qmd
    right:
      - icon: twitter
        href: https://twitter.com/iamthinhong/
      - icon: github
        href: https://github.com/thinhong
      - icon: linkedin
        href: https://www.linkedin.com/in/thinh-ong
        
format:
  html:
    theme: [litera, theme.scss]
    toc: true

comments:
  giscus:
    repo: thinhong/thinhong.github.io


