project:
  type: website
  resources:
    - CNAME
  output-dir: docs

website:
  favicon: logo-icon.svg
  google-analytics: "G-RVRBE7Y1R2"
  back-to-top-navigation: true
  navbar:
    logo: logo.svg
    left:
      - text: About
        href: about/index.qmd
      - text: Research
        href: https://scholar.google.com/citations?user=PkfvVs0AAAAJ
      - text: Talks
        href: talks/index.qmd
      - text: Teaching
        href: teaching/index.qmd
      - text: Software
        href: software/index.qmd
      - text: Blog
        href: blog/index.qmd
    right:
      - icon: twitter
        href: https://twitter.com/iamthinhong/
      - icon: github
        href: https://github.com/thinhong
      - icon: linkedin
        href: https://www.linkedin.com/in/thinh-ong
        
format:
  html:
    theme: [cosmo, theme.scss]

comments:
  giscus:
    repo: thinhong/thinhong.github.io


